<Project>
  <PropertyGroup>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <VersionPrefix>1.0.0</VersionPrefix>
    <Company>VisDir contributors</Company>
    <Product>VisDir</Product>
    <Copyright>Copyright © 2026 VisDir contributors</Copyright>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors Condition="'$(CI)' == 'true'">true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
