<Project>
  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <AccelerateBuildsInVisualStudio>true</AccelerateBuildsInVisualStudio>
    <VersionPrefix>1.1.1</VersionPrefix>
    <Company>VisDir contributors</Company>
    <Product>VisDir</Product>
    <Copyright>Copyright © 2026 VisDir contributors</Copyright>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(CI)' == 'true'">true</ContinuousIntegrationBuild>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
